### ISSUE TITLE
_fill_gt and _fill_lt not handled properly

### ISSUE THREAD

**Issue by mircuz** [lamkashingpaul/backtrader_plotly#1]
Hi,
awesome work! I spotted a bug when you try to plot indicators which have shadows, like in the case of Ichimoku clouds.
Plotly does not handle properly `_fill_gt` nor `_fill_lt`, causing a crash. 
Here a snippet which cause the error
```
plotlines = dict(
        senkou_span_a=dict(_fill_gt=('senkou_span_b', 'g'),
                           _fill_lt=('senkou_span_b', 'r')),
    )
```
Can you fix it or suggest a solution?

Best regards
Mirco

**Comment by lamkashingpaul** [comment]
Hi, I'm glad you liked it and found that the package is useful. As you may realize, I had gone through the plotting logic and tried to replace only the original `matplotlib` functions I encountered with equivalent `plotly` functions. There might be still functions that are not handled as I had never touched them in my case.

After revisiting the original package, I found that area fills generated by some indicators like Ichimoku and haDelta, were still handled by some abandoned `matplotlib` function calls which caused the crash. I tried to implement the area-filling logic using `plotly` and I will officially update the package after testing.

Btw, you may find the details at the `dev` branch, or simply install it by running `pip install backtrader-plotly==1.4.0.dev1` and try it out first. See if it is working as the provided example shown below.

![newplot (12)](https://user-images.githubusercontent.com/35261006/200133131-42f69db6-b3f8-4544-afbe-fcb72b325692.png)

**Comment by mircuz** [comment]
Awesome work, thank you so much!
