### ISSUE TITLE
Support for multiple strategies?

### ISSUE THREAD

**Issue by WheatMaThink** [lamkashingpaul/backtrader_plotly#2]
Hi, friend

awesome work! Whether the following call methods are supported,
multiple strategies？

cerebro.addstrategy(IchimokuStrategy)
cerebro.addstrategy(SMAStrategy)

thanks。

**Comment by lamkashingpaul** [comment]
Hi, I am glad to hear that, and I have to say that the package is not plotting figures of multiple strategies at the moment.

While I am happy to continue working on this project and make it behave as close as possible to the original one, I did a quick fix and I am currently testing it.

Although it shall be released officially soon after testing, you may first install and try it out by running the following command.
`pip install backtrader-plotly==1.5.0.dev1`. An updated working example is also available [here](https://github.com/lamkashingpaul/backtrader_plotly/commit/372abeac44707d16dfe9838b32709bb13c223c45) in the `dev` branch.

Please feel to drop any comments.

**Comment by WheatMaThink** [comment]
This is a great feature and improvement!
